jad --source-only "org.springframework.web.servlet.handler.ConversionServiceExposingInterceptor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.resource.ResourceUrlProviderExposingInterceptor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "com.madaha.codesecmemshell.controller.InterceptorMemShell$Shell_Interceptor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "com.madaha.codesecmemshell.controller.DemoController" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "sun.reflect.NativeMethodAccessorImpl" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "sun.reflect.NativeMethodAccessorImpl" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "sun.reflect.DelegatingMethodAccessorImpl" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "java.lang.reflect.Method" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.method.support.InvocableHandlerMethod" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.method.support.InvocableHandlerMethod" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.DispatcherServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.DispatcherServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.FrameworkServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.FrameworkServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "javax.servlet.http.HttpServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.servlet.FrameworkServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "javax.servlet.http.HttpServlet" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.tomcat.websocket.server.WsFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.jsp.Filter_005fShell_jsp$Shell_Filter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.RequestContextFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.OncePerRequestFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.FormContentFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.OncePerRequestFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.CharacterEncodingFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.springframework.web.filter.OncePerRequestFilter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.ApplicationFilterChain" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.StandardWrapperValve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.StandardContextValve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.jsp.Valve_005fShell_jsp$Shell_Valve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.authenticator.AuthenticatorBase" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.StandardHostValve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.valves.ErrorReportValve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.core.StandardEngineValve" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.catalina.connector.CoyoteAdapter" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.coyote.http11.Http11Processor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.coyote.AbstractProcessorLight" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.coyote.AbstractProtocol$ConnectionHandler" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.tomcat.util.net.NioEndpoint$SocketProcessor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.tomcat.util.net.SocketProcessorBase" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "java.util.concurrent.ThreadPoolExecutor" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "java.util.concurrent.ThreadPoolExecutor$Worker" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"
jad --source-only "java.lang.Thread" | grep -C 3 -e "((?!RuntimeException)(Runtime|ProcessBuilder|ClassLoader|getClassLoader|crypto|Cipher))+?"
echo "-----------------------------------------------"